# Generated by Django 4.0 on 2022-05-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0045_remove_course_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='liked',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
