# Generated by Django 4.0 on 2022-05-08 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0046_course_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='a',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
